Repository wecode-bootcamp-korea/enter_cloud-backend, pull requests merged in 2021-01, with the labels that each got.

#1 ADD: models.py 작성
  .gitignore
  enter_cloud/settings.py
  enter_cloud/urls.py
  qna/__init__.py
  qna/admin.py
  qna/apps.py
  qna/migrations/0001_initial.py
  qna/migrations/__init__.py
  qna/models.py
  qna/tests.py
  qna/views.py
  reviews/__init__.py
  reviews/admin.py
  reviews/apps.py
  reviews/migrations/0001_initial.py
  reviews/migrations/0002_auto_20210113_1106.py
  reviews/migrations/__init__.py
  reviews/models.py
  reviews/tests.py
  reviews/views.py
  spaces/.DS_Store
  spaces/__init__.py
  spaces/admin.py
  spaces/apps.py
  spaces/migrations/0001_initial.py
  spaces/migrations/0002_auto_20210113_1550.py
  spaces/migrations/0003_auto_20210113_1741.py
  spaces/migrations/__init__.py
  spaces/models.py
  spaces/tests.py
  spaces/views.py
  users/__init__.py
  users/admin.py
  users/apps.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210113_1741.py
  users/migrations/__init__.py
  users/models.py
  users/tests.py
  users/views.py
  utils.py
Labels: Status: 도움 요청

#2 ADD: 회원가입, 로그인
  enter_cloud/urls.py
  pull_request_template.md
  users/migrations/0003_remove_user_login_method.py
  users/urls.py
  users/views.py
Labels: Status: Accepted

#3 [Feature/database] 데이터 베이스 구축 커맨드
  qna/migrations/0001_initial.py
  reviews/management/commands/__init__.py
  reviews/management/commands/seed_reviews.py
  reviews/migrations/0001_initial.py
  reviews/migrations/0002_auto_20210113_1106.py
  spaces/management/commands/__init__.py
  spaces/management/commands/seed_options.py
  spaces/management/commands/seed_spaces.py
  spaces/migrations/0001_initial.py
  spaces/migrations/0002_auto_20210113_1550.py
  spaces/migrations/0002_auto_20210114_1843.py
  spaces/migrations/0003_auto_20210113_1741.py
  spaces/models.py
  users/management/commands/__init__.py
  users/management/commands/seed_users.py
  users/migrations/0001_initial.py
  users/migrations/0002_auto_20210113_1741.py
  users/migrations/0003_remove_user_login_method.py
Labels: Status: Accepted

#4 ADD: 메인페이지 카드, 리뷰카드
  enter_cloud/urls.py
  reviews/management/commands/seed_reviews.py
  spaces/management/commands/seed_detail_spceas.py
  spaces/management/commands/seed_options.py
  spaces/management/commands/seed_spaces.py
  spaces/urls.py
  spaces/views.py
  users/management/commands/seed_users.py
Labels: Status: 리뷰 진행중

#5 ADD: 상세정보 페이지 추가
  decorators/utils.py
  enter_cloud/urls.py
  reviews/urls.py
  reviews/views.py
  spaces/management/commands/seed_spaces.py
  spaces/urls.py
  spaces/views.py
  users/views.py
Labels: Status: 리뷰 요청

#7 ADD: 유저 좋아요 기능 추가, MODIFY: 데이터베이스 초기화후 마이그레이션
  qna/migrations/0001_initial.py
  reviews/migrations/0001_initial.py
  reviews/views.py
  spaces/management/commands/seed_detail_spaces.py
  spaces/management/commands/seed_options.py
  spaces/migrations/0001_initial.py
  spaces/migrations/0002_auto_20210114_1843.py
  spaces/migrations/0002_like_is_liked.py
  spaces/models.py
  spaces/urls.py
  spaces/views.py
  users/migrations/0001_initial.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#8 [Feature/modify] 진행상황 변경으로 수정
  qna/migrations/0001_initial.py
  reviews/migrations/0001_initial.py
  reviews/urls.py
  reviews/views.py
  spaces/management/commands/seed_detail_spaces.py
  spaces/management/commands/seed_options.py
  spaces/management/commands/seed_spaces.py
  spaces/migrations/0001_initial.py
  spaces/migrations/0002_like_is_liked.py
  spaces/models.py
  spaces/urls.py
  spaces/views.py
  users/management/commands/seed_users.py
  users/migrations/0001_initial.py
  users/views.py
Labels: Status: Accepted

#9 ADD 메인카드뷰 페이지네이션 추가
  reviews/views.py
  spaces/urls.py
  spaces/views.py
Labels: Status: Accepted

#10 ADD: 검색기능 추가
  qna/migrations/0001_initial.py
  qna/migrations/__init__.py
  reviews/migrations/0001_initial.py
  spaces/management/commands/seed_detail_spaces.py
  spaces/management/commands/seed_spaces.py
  spaces/migrations/0001_initial.py
  spaces/urls.py
  spaces/views.py
  users/migrations/0001_initial.py
Labels: Status: Accepted
